### ISSUE TITLE
Could not import DFG-Viewer example (caused by image URL with redirect?)

### ISSUE THREAD

**Issue by stweil** [jbaiter/demetsiiify#8]
While trying to process the [BSB example](http://dfg-viewer.de/show/?tx_dlf%5Bid%5D=http%3A%2F%2Fdaten.digitale-sammlungen.de%2F~db%2Fmets%2Fbsb00020619_mets.xml), the METS import fails:

    [...]
      File "/code/demetsiiify/mets.py", line 376, in image_info
        'mimetype': server_mime}) from exc
    demetsiiify.mets.MetsImportError: Could not open image from http://daten.digitale-sammlungen.de/~db/0002/bsb00020619/images/150/bsb00020619_00015.jpg, likely the server sent corrupt data.
    [...]

The image link works in a web browser and redirects to a different web page.

_demetsiiify_ shows an error message with missing information:

     Unfortunately we were unable to generate a IIIF manifest from the METS located at
    
                                                               .
    
    The error was logged in our backend and will be examined. If you wish to help with debugging, you can consult the traceback below and open an issue on GitHub.

**Comment by stweil** [comment]
In the meantime I also noticed that _demetsiiiify_ cannot import from https links.

**Comment by stweil** [comment]
There seems also to be a problem when the images use https links.

**Comment by jbaiter** [comment]
So I finally got around to looking at this after doing some refactoring. I can't reproduce it locally with the new code, so either I inadvertently fixed the bug that caused the redirects and HTTPS not to work, or it's due to the setup on the production server. I have a few more urgently needed maintenance work I need to do on the code, but the app should be up and running on the new server by Sunday at the lastest, then we'll see if it actually works :-)

Btw, if you wait until mid-2019, we'll hopefully most of the remaining volumes at the BSB online with proper IIIF support :-)

**Comment by stweil** [comment]
A new test with the latest code from Git master works, so this issue can be closed. Thank you!
